# Generated by Django 5.0.6 on 2024-06-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_predmeti_nositelj'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upisi',
            unique_together={('student', 'predmet')},
        ),
    ]
